apiVersion: v1
kind: ConfigMap
metadata:
  name: cachet-config
  namespace: monitoring
  labels:
    app: cachet
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_LOG: "single"
  APP_URL: "https://status.hippius.com"
  DB_DRIVER: "sqlite"
  FORCE_MIGRATION: "true"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_DRIVER: "sync"
  MAIL_DRIVER: "log"
