apiVersion: v1
kind: ConfigMap
metadata:
  name: cachet-config
  namespace: monitoring
  labels:
    app: cachet
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://cachet.monitoring.svc.cluster.local"
  DB_DRIVER: "sqlite"
  DB_DATABASE: "/var/www/html/database/database.sqlite"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_DRIVER: "sync"
  MAIL_DRIVER: "log"
