apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cachet-sqlite
  namespace: monitoring
  labels:
    app: cachet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
