apiVersion: v1
kind: Service
metadata:
  name: cachet
  namespace: monitoring
  labels:
    app: cachet
spec:
  type: ClusterIP
  selector:
    app: cachet
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
