apiVersion: v1
kind: ConfigMap
metadata:
  name: hippius-s3-environment
data:
  ENVIRONMENT: "staging"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging,service.namespace=hippius-s3-staging"
