apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hippius-s3-staging

resources:
  - ../base
  - gateway-nodeport.yaml
  - postgres-objectstore.yaml

patchesStrategicMerge:
  - namespace-patch.yaml
  - environment-patch.yaml
  - resource-limits.yaml

images:
  - name: ghcr.io/thenervelab/hippius-s3/api
    newTag: latest
  - name: ghcr.io/thenervelab/hippius-s3/gateway
    newTag: latest
  - name: ghcr.io/thenervelab/hippius-s3/workers
    newTag: latest
