apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: hippius-s3-staging
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: hippius-s3-staging
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  namespace: hippius-s3-staging
spec:
  replicas: 5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-cache-pvc
  namespace: hippius-s3-staging
spec:
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-pvc
  namespace: hippius-s3-staging
spec:
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlq-pvc
  namespace: hippius-s3-staging
spec:
  resources:
    requests:
      storage: 10Gi
