apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-uploader
spec:
  template:
    spec:
      containers:
        - name: ipfs-uploader
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-uploader
spec:
  template:
    spec:
      containers:
        - name: arion-uploader
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-downloader
spec:
  template:
    spec:
      containers:
        - name: ipfs-downloader
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-downloader
spec:
  template:
    spec:
      containers:
        - name: arion-downloader
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-unpinner
spec:
  template:
    spec:
      containers:
        - name: ipfs-unpinner
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-unpinner
spec:
  template:
    spec:
      containers:
        - name: arion-unpinner
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
