apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 4
  kubernetesConfig:
    resources:
      requests:
        cpu: 2000m
        memory: 52Gi
      limits:
        cpu: 8000m
        memory: 52Gi
    redisConfig:
      maxmemory: "50gb"
