apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: gateway
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-uploader
spec:
  template:
    spec:
      containers:
        - name: ipfs-uploader
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-uploader
spec:
  template:
    spec:
      containers:
        - name: arion-uploader
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-downloader
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ipfs-downloader
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-downloader
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: arion-downloader
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-unpinner
spec:
  template:
    spec:
      containers:
        - name: ipfs-unpinner
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arion-unpinner
spec:
  template:
    spec:
      containers:
        - name: arion-unpinner
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-cacher
spec:
  template:
    spec:
      containers:
        - name: account-cacher
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitor
spec:
  template:
    spec:
      containers:
        - name: janitor
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-cache-pvc
spec:
  resources:
    requests:
      storage: 9728Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-pvc
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlq-pvc
spec:
  resources:
    requests:
      storage: 20Gi
