apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: hippius-s3-prod
spec:
  replicas: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: hippius-s3-prod
spec:
  replicas: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  namespace: hippius-s3-prod
spec:
  replicas: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orphan-checker
  namespace: hippius-s3-prod
spec:
  replicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-cache-pvc
  namespace: hippius-s3-prod
spec:
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-pvc
  namespace: hippius-s3-prod
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlq-pvc
  namespace: hippius-s3-prod
spec:
  resources:
    requests:
      storage: 20Gi
