apiVersion: v1
kind: ConfigMap
metadata:
  name: hippius-s3-environment
  namespace: hippius-s3-staging
data:
  ENVIRONMENT: "staging"
  LOKI_URL: "http://loki.hippius-monitoring:3100/loki/api/v1/push"
  HOST_BIND_IP: "0.0.0.0"
  HIPPIUS_OBJECT_CACHE_DIR: "/var/lib/hippius/object_cache"
  PYTHONUNBUFFERED: "1"
  ENABLE_WATCHFILES: "false"
