apiVersion: v1
kind: ConfigMap
metadata:
  name: hippius-s3-defaults
data:
  RATE_LIMIT_PER_MINUTE: "600"
  MAX_REQUEST_SIZE_MB: "100"
  MIN_BUCKET_NAME_LENGTH: "3"
  MAX_BUCKET_NAME_LENGTH: "100"
  MAX_OBJECT_KEY_LENGTH: "1024"
  MAX_METADATA_SIZE: "200"
  LOG_LEVEL: "INFO"
  LOKI_ENABLED: "false"
  ENABLE_MONITORING: "true"
  HOST: "0.0.0.0"
  PORT: "8000"
  DEBUG: "false"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_API_DOCS: "true"
  DOCS_CACHE_TTL_SECONDS: "300"
  ENABLE_REQUEST_PROFILING: "false"
  ENABLE_BANHAMMER: "true"
  HIPPIUS_BYPASS_CREDIT_CHECK: "false"
  HIPPIUS_SUBSTRATE_URL: "wss://rpc.hippius.network"
  HIPPIUS_VALIDATOR_REGION: "decentralized"
  HIPPIUS_IPFS_MAX_RETRIES: "1"
  HIPPIUS_UPLOADER_MAX_ATTEMPTS: "2"
  HIPPIUS_UPLOADER_BACKOFF_BASE_MS: "100"
  HIPPIUS_UPLOADER_BACKOFF_MAX_MS: "500"
  HIPPIUS_UNPINNER_MAX_ATTEMPTS: "5"
  HIPPIUS_UNPINNER_BACKOFF_BASE_MS: "1000"
  HIPPIUS_UNPINNER_BACKOFF_MAX_MS: "60000"
  ORPHAN_CHECKER_LOOP_SLEEP: "7200"
  ORPHAN_CHECKER_BATCH_SIZE: "100"
  HIPPIUS_ORPHAN_WORKER_ACCOUNT_WHITELIST: ""
  HTTP_STREAM_INITIAL_TIMEOUT_SECONDS: "0.5"
  HIPPIUS_DLQ_DIR: "/tmp/hippius_dlq"
  HIPPIUS_DLQ_ARCHIVE_DIR: "/tmp/hippius_dlq_archive"
  GATEWAY_DB_POOL_MIN_SIZE: "10"
  GATEWAY_DB_POOL_MAX_SIZE: "100"
  GATEWAY_DB_POOL_MAX_QUERIES: "50000"
  GATEWAY_DB_POOL_MAX_INACTIVE_LIFETIME: "300"
  GATEWAY_DB_POOL_COMMAND_TIMEOUT: "30"
  API_DB_POOL_MIN_SIZE: "5"
  API_DB_POOL_MAX_SIZE: "20"
  API_DB_POOL_MAX_QUERIES: "50000"
  API_DB_POOL_MAX_INACTIVE_LIFETIME: "300"
  API_DB_POOL_COMMAND_TIMEOUT: "30"
  CACHET_API_URL: "http://cachet.monitoring.svc.cluster.local"
  BACKUP_INTERVAL_HOURS: "24"
  BACKUP_RETENTION_COUNT: "30"
  HIPPIUS_API_BASE_URL: "https://api.hippius.com/api"
  ACL_CACHE_TTL_SECONDS: "600"
  ENABLE_PUBLIC_READ: "true"
  PUBLISH_TO_CHAIN: "true"
  ENABLE_STRICT_VALIDATION: "true"
  HIPPIUS_TARGET_STORAGE_VERSION: "5"
  HIPPIUS_PINNER_CONSUME_QUEUE: "upload_requests"
  HIPPIUS_KMS_MODE: "required"
  HIPPIUS_OVH_KMS_CERT_PATH: "/kms_certs/client.crt"
  HIPPIUS_OVH_KMS_KEY_PATH: "/kms_certs/client.key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "delta"
  OTEL_SERVICE_NAME: "hippius-s3"
