apiVersion: v1
kind: ConfigMap
metadata:
  name: hippius-s3-defaults
data:
  FRONTEND_HMAC_SECRET: "test_secret"
  RATE_LIMIT_PER_MINUTE: "100000"
  MAX_REQUEST_SIZE_MB: "512"
  MIN_BUCKET_NAME_LENGTH: "3"
  MAX_BUCKET_NAME_LENGTH: "63"
  MAX_OBJECT_KEY_LENGTH: "1024"
  MAX_METADATA_SIZE: "2048"
  LOG_LEVEL: "INFO"
  LOKI_ENABLED: "false"
  ENABLE_MONITORING: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  DEBUG: "false"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_API_DOCS: "true"
  DOCS_CACHE_TTL_SECONDS: "300"
  ENABLE_REQUEST_PROFILING: "false"
  ENABLE_BANHAMMER: "true"
  HIPPIUS_BYPASS_CREDIT_CHECK: "false"
  HIPPIUS_SUBSTRATE_URL: "wss://rpc.hippius.network"
  HIPPIUS_VALIDATOR_REGION: "decentralized"
  HIPPIUS_IPFS_MAX_RETRIES: "1"
  HIPPIUS_UPLOADER_MAX_ATTEMPTS: "2"
  HIPPIUS_UPLOADER_BACKOFF_BASE_MS: "100"
  HIPPIUS_UPLOADER_BACKOFF_MAX_MS: "500"
  HIPPIUS_UNPINNER_MAX_ATTEMPTS: "5"
  HIPPIUS_UNPINNER_BACKOFF_BASE_MS: "1000"
  HIPPIUS_UNPINNER_BACKOFF_MAX_MS: "60000"
  ORPHAN_CHECKER_LOOP_SLEEP: "7200"
  ORPHAN_CHECKER_BATCH_SIZE: "100"
  HIPPIUS_ORPHAN_WORKER_ACCOUNT_WHITELIST: ""
  HTTP_STREAM_INITIAL_TIMEOUT_SECONDS: "0.5"
  HIPPIUS_DLQ_DIR: "/tmp/hippius_dlq"
  HIPPIUS_DLQ_ARCHIVE_DIR: "/tmp/hippius_dlq_archive"
  GATEWAY_DB_POOL_MIN_SIZE: "10"
  GATEWAY_DB_POOL_MAX_SIZE: "100"
  GATEWAY_DB_POOL_MAX_QUERIES: "50000"
  GATEWAY_DB_POOL_MAX_INACTIVE_LIFETIME: "300"
  GATEWAY_DB_POOL_COMMAND_TIMEOUT: "30"
  API_DB_POOL_MIN_SIZE: "5"
  API_DB_POOL_MAX_SIZE: "20"
  API_DB_POOL_MAX_QUERIES: "50000"
  API_DB_POOL_MAX_INACTIVE_LIFETIME: "300"
  API_DB_POOL_COMMAND_TIMEOUT: "30"
  CACHET_API_URL: "https://status.example.com"
  CACHET_API_KEY: "your-cachet-api-key-here"
  CACHET_COMPONENT_ID: "1"
  BACKUP_INTERVAL_HOURS: "24"
  BACKUP_RETENTION_COUNT: "30"
  HIPPIUS_API_BASE_URL: "https://api.hippius.com/api"
  ACL_CACHE_TTL_SECONDS: "600"
