apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-defaults.yaml
  - configmap-redis.yaml
  - configmap-environment.yaml
  - pvc-shared.yaml
  - postgres-statefulset.yaml
  - redis-statefulsets.yaml
  - ipfs-statefulset.yaml
  - migration-job.yaml
  - api-deployment.yaml
  - gateway-deployment.yaml
  - workers-deployments.yaml
  - services.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
