apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 2
  clusterVersion: v7
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: false
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 500m
        memory: 12Gi
      limits:
        cpu: 2000m
        memory: 12Gi
    redisConfig:
      maxmemory: "10gb"
      maxmemory-policy: "allkeys-lru"
      maxmemory-samples: "10"
      maxclients: "10000"
      databases: "1"
      tcp-backlog: "2048"
      tcp-keepalive: "300"
      timeout: "0"
      hz: "100"
      lazyfree-lazy-eviction: "yes"
      lazyfree-lazy-expire: "yes"
      lazyfree-lazy-server-del: "yes"
      activedefrag: "yes"
      active-defrag-ignore-bytes: "100mb"
      active-defrag-threshold-lower: "10"
      active-defrag-threshold-upper: "100"
      active-defrag-cycle-min: "1"
      active-defrag-cycle-max: "25"
      protected-mode: "no"
      rename-command-FLUSHDB: '""'
      rename-command-FLUSHALL: '""'
      rename-command-DEBUG: '""'
  serviceType: ClusterIP
